### PR TITLE
Added cloudfront invalidation step during deployment.

### PR DESCRIPTION
**Pull request by sahataba**

### CODE REVIEW

**Review by pviarkhouski — APPROVED** [review]

**Review by alexremn — CHANGES_REQUESTED** [review]
@sahataba please, add --delete to all s3 sync operations, so files, which we have no locally, would be deleted from the bucket.
Also, its better to go with env vars in terms of profile and distribution ID.

**Comment by sahataba** [comment]
@alexremn Can you suggest some approach with env variables? I'm not proficient with bash scripts.
Or we could add them later, when we add CI/CD job for it. cc: @evgeny-s

**Comment by alexremn** [comment]
@sahataba I see no issue to add CI/CD pipelines for this service. We can start with creating a ticket in devops project, then ill do it today.

**Comment by alexremn** [comment]
@sahataba I see no issue to add CI/CD pipelines for this service. We can start with creating a ticket in devops project, then ill do it today.
What about bash envs, it would just make life easier for multiple people working on this project. If we would implement cicd for it, there would no deploy scripts even required.

**Review by alexremn — APPROVED** [review]

**Pull request merged**
